[package]
name = "tensoraudio"
description = "Reading and writing WAV files to and from tch-rs compatible tensors"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Liam Power <info@liampower.dev>"]

[dependencies]
anyhow = "1.0.95"
clio = { version = "0.3.5", features = ["clap-parse"] }
hound = "3.5.1"
log = "0.4.25"
rand = "0.9.0"
tch = "0.19.0"

[dev-dependencies]
clap = { version = "4.5.29", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
